name = "Fracciones"
uuid = "81451a68-6ad1-41c9-8c04-09494141aeca"
authors = ["Helios De Rosario "]
version = "0.1.0"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
julia = "1"
MacroTools = "0.5"
